settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: philip.twinight.co/portfolio
    description: 'Project Poftfolio' # default=empty
    url: 'https://philip.twinight.co/portfolio' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: twinight-co
    name: twinight.co
    description: 'Company website.'
    url: 'https://twinight.co'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: philip-twinight-co
    name: Old Portfolio
    url: 'https://philip.twinight.co/'
    method: GET
    expectStatus: 200
