settings:
  title: 'Status Page'
  url: 'https://status.twinight.co' # used for Slack messages
  logo: https://philip.twinight.co/images/logo_p1.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: project-portfolio # unique identifier
    name: Philip’s Data Science Diary
    url: 'https://philip.twinight.co/portfolio/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: twinight-co
    name: Twinight Limited
    url: 'https://twinight.co/'
    method: GET
    expectStatus: 200

  - id: philip-twinight-co
    name: Philip's Old Portfolio
    url: 'https://philip.twinight.co/'
    method: GET
    expectStatus: 200
